[package]
name = "unwx"
version = "0.4.0"
edition = "2024"
readme = "README.md"
description = "unpack wxapkg easily."
homepage = "https://github.com/unbyte/unwx"
repository = "https://github.com/unbyte/unwx"
keywords = ["wxapkg"]
categories = ["command-line-utilities"]
license = "MIT"
authors = ["unbyte <i@shangyes.net>"]

[lib]
name = "unwx"

[[bin]]
name = "unwx"
required-features = ["cli"]

[features]
default = ["cli"]
cli = ["dep:xflags"]

[dependencies]
rayon = "1.12"
thiserror = "2"
xflags = { version = "0.3", optional = true }

[target.'cfg(windows)'.dependencies]
pbkdf2 = "0.12"
sha1 = "0.10"
aes = "0.8"
cbc = "0.1"

[profile.release]
codegen-units = 1
lto = true
strip = true
panic = "abort"
